#!/usr/bin/env python

import sys, re, os
from rapyd.compiler import parse_file, finalize_source

if __name__ == "__main__":
	orig_dir = os.getcwd()
	base_dir, orig_file = os.path.split(sys.argv[1])
	filename = orig_file.rsplit('.', 1)[0] # remove the extension

	if base_dir:
		os.chdir(base_dir)
	
	source = parse_file(orig_file)
	with open(filename + '.js', 'w') as new_file:
		new_file.write(source)
	os.chdir(orig_dir)
